### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function add_lang() 

### ISSUE THREAD

**Issue by PatriceVigier** [AlexSheer/phpBB3.2-STK#57]
Support Toolkit for phpBB3.2.x
PHPBB 3.2.5
PHP 7.3

When I select user/group tools > Removing users I get the following error

Fatal error: Uncaught Error: Call to a member function add_lang() on null in /xxxx/delete_users.php:108 Stack trace: #0 /xxx/index.php(301): delete_users->display_options() #1 {main} thrown in /xxx/delete_users.php on line 108
Error 1: Uncaught Error: Call to a member function add_lang() on null in /xxx/delete_users.php:108 Stack trace: #0 /xxx/index.php(301): delete_users->display_options() #1 {main} thrown at file /xxx/delete_users.php line 108

What can I do?
Thank you

**Comment by AlexSheer** [comment]
![изображение](https://user-images.githubusercontent.com/9640205/128183140-9dcc7c33-33a3-4d89-90d0-70c1812465b4.png)
