### ISSUE TITLE
Fatal error: Uncaught Twig\Error\LoaderError: Unable to find template "cron.html" phpBB 3.3.8

### ISSUE THREAD

**Issue by ssl-origin** [AlexSheer/phpBB3.2-STK#60]
Hi Alex

This error with phpBB 3.3.8 and last version of STK

`Fatal error: Uncaught Twig\Error\LoaderError: Unable to find template "cron.html" (looked into: /home/gach9794/public_html/forum/tools/style). in /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php:250 Stack trace: #0 /home/gach9794/public_html/forum/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('cron.html', true) #1 /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('cron.html') #2 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(299): Twig\Loader\FilesystemLoader->getCacheKey('cron.html') #3 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('cron.html') #4 /home/gach9794/public_html/forum/phpbb/template/twig/environment.php(277): Twig\Environment->loadTemplate('cron.html', NULL) #5 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(359): phpbb\template\twig\environment->loadTemplat in /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250
Error 1: Uncaught Twig\Error\LoaderError: Unable to find template "cron.html" (looked into: /home/gach9794/public_html/forum/tools/style). in /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php:250 Stack trace: #0 /home/gach9794/public_html/forum/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('cron.html', true) #1 /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('cron.html') #2 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(299): Twig\Loader\FilesystemLoader->getCacheKey('cron.html') #3 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(381): Twig\Environment->getTemplateClass('cron.html') #4 /home/gach9794/public_html/forum/phpbb/template/twig/environment.php(277): Twig\Environment->loadTemplate('cron.html', NULL) #5 /home/gach9794/public_html/forum/vendor/twig/twig/src/Environment.php(359): phpbb\template\twig\environment->loadTemplat at file /home/gach9794/public_html/forum/vendor/twig/twig/src/Loader/FilesystemLoader.php line 250
`

**Comment by toxyy** [comment]
Temporary workaround I'm using is to copy the `index.htm` file and rename it to `cron.html`. Probably not the best long term solution but it let me use the tool for what I needed it for.

**Comment by ssl-origin** [comment]
Hi toxyy
Solution already proposed on my forum: https://forums.caforum.fr/viewtopic.php?p=4642#p4642

A patch has just been made by Татьяна5 to fix the problems with phpBB 3.3.8: https://github.com/Tatiana5/phpBB3.2-STK

**Comment by digdilem** [comment]
Quick note to say thanks for this - solution. This issue took down my board this morning after an otherwise successful upgrade to latest version of phpbb. Don't know how or why, and that file wasn't present in the previous installation either.

Quickfix for me: `touch cron.html` in one of the directories Apache's error log says that Twig searched in.
